[Welcome2Air] pdf생성 및 S3 및 Database에 저장 기능구현 완료
wecode-bootcamp-korea/21-2nd-Welcome-2-Air-backend pull request #12
Opened 2021-06-30 12:31 UTC by dlwjdals5600

1. pdf C3,데이터베이스에 저장 기능 구현

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- pdf파일을 S3와 Databases에 저장 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- views.py의 데이터를 html에 데이터 동적 치환 기능 구현
- pdfkit을 이용한 html을 pdf 변환 기능 구현
- ContentFile을 이용한 pdf파일화 시켜 AWS S3에 저장 기능 구현
- S3에 저장 된 후 저장된 pdf파일 주소를 Databases에 저장하는 기능 구현

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 경훈님 감사합니다. 덕분에 많이 배웠고 재밌는 기능을 구현할 수 있었습니다!! 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-06-30 15:08 UTC, Kang-kyunghun requested changes

2021-06-30 15:08 UTC, Kang-kyunghun commented on tickets/urls.py
> +    path('/pdfUpload', FileView.as_view()),
```suggestion
    path('/pdf', FileView.as_view()),
```

2021-06-30 15:08 UTC, Kang-kyunghun commented on tickets/views.py
> +class FileView(View):
```suggestion
class TicketPdfView(View):
```

2021-06-30 15:08 UTC, Kang-kyunghun commented on tickets/views.py
> +        content    = dict()
```suggestion
```
없어도 될 것 같아요

2021-06-30 15:08 UTC, Kang-kyunghun commented on tickets/views.py
> +            file_url = f"https://s3.ap-northeast-2.amazonaws.com/{'welcome2air'}/{welcome2air_tickets}"
```suggestion
            file_url = f"https://welcome2air.s3.ap-northeast-2.amazonaws.com/{'welcome2air'}/{welcome2air_tickets}"
```
버킷 이름 앞에 붙어야 되지 않아요?

2021-06-30 15:08 UTC, Kang-kyunghun commented on tickets/views.py
> +        return HttpResponse(status= 200)
JsonResponse로 바꿔주세요.

2021-07-01 01:01 UTC, dlwjdals5600 commented on tickets/urls.py
> +    path('/pdfUpload', FileView.as_view()),
urls.py 에서 pdf로 변경 완료했습니다.

2021-07-01 01:01 UTC, dlwjdals5600 commented on tickets/views.py
> +class FileView(View):
클래스 명 TicketPdfView로 변경 했습니다.

2021-07-01 01:02 UTC, dlwjdals5600 commented on tickets/views.py
> +        content    = dict()
넵! 수정 완료했습니다. 고친다는걸 잊고 있었네욤..

2021-07-01 01:04 UTC, dlwjdals5600 commented on tickets/views.py
> +            file_url = f"https://s3.ap-northeast-2.amazonaws.com/{'welcome2air'}/{welcome2air_tickets}"
제가 databases에 저장된 주소를 시험해보니깐 잘 나와서 고치지는 않았습니다. 저희 팀원분들에게도 붙여 넣기 해도 pdf가 잘 떴습니다.

2021-07-01 01:04 UTC, dlwjdals5600 commented on tickets/views.py
> +        return HttpResponse(status= 200)
네! 수정 완료했습니다.

2021-07-01 06:32 UTC, Kang-kyunghun commented
고생 많으셨습니다.!!

2021-07-01 06:32 UTC, merged