ADD : 항공편 조회 views.py 추가, 검색필터링 및  조회
wecode-bootcamp-korea/21-2nd-Welcome-2-Air-backend pull request #7
Opened 2021-06-28 12:36 UTC by ttakku-park

1. 조회,필터링 기능 url 추가
2. FlightListView class 작성 필터링 및 조회 기능

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 메인페이지의 국가 선택 조회 리스트 작성 FlightCountryListView
- 프론트와의 키값 이슈가 있어 화요일 수정예정입니다. 

- 필터링 및 필터링 결과 조회 FlightListView
- 쿼리스트링으로 받아 Q 객체 필터링 구현 , 현재 시간 이전의 결과 값은 조회하지 않기위해 Q(departure_datetime__date__gt = today)& 사용

-테스트케이스 아직 작성 전 입니다!

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-06-28 13:39 UTC, Kang-kyunghun requested changes

2021-06-28 13:39 UTC, Kang-kyunghun commented on flights/views.py
> +
불필요한 공백은 제거해 주세요.

2021-06-28 13:39 UTC, Kang-kyunghun commented on flights/views.py
> +                                'seat_stock'            :flight.flight_seat_flight.get(seat__name=seat_name).stock
일단은 같이 확인 했던 부분인데, get을 사용하는 것이 걸리네요. 이 부분은 저랑 같이 더 얘기해 봐요

2021-06-28 13:39 UTC, Kang-kyunghun commented on flights/views.py
> +            print(seat_name)
print 제거해 주세요.

2021-06-28 13:39 UTC, Kang-kyunghun commented on flights/views.py
> +                Q(departure_datetime__date__gt = today)&
오늘 날짜 이전 비행 일정에 대해서도 제가 처음에는 filter에 추가 하자고 했는데, data 받은 뒤에 오늘 날짜랑 출발 날짜랑 비교해서 예외처리 하는 것은 어떨까요?

2021-06-28 13:39 UTC, Kang-kyunghun commented on flights/views.py
> +
공백은 1칸으로 해주세요.

2021-06-29 06:18 UTC, ttakku-park commented on flights/views.py
> +
제거하겠습니다!

2021-06-29 06:19 UTC, ttakku-park commented on flights/views.py
> +                                'seat_stock'            :flight.flight_seat_flight.get(seat__name=seat_name).stock
넵 저도 계속 찾아보겠습니다

2021-06-29 06:19 UTC, ttakku-park commented on flights/views.py
> +            print(seat_name)
아이쿠,, 확인을 못했네요 제거하겠습니다!

2021-06-30 11:44 UTC, Kang-kyunghun commented
고생 정말 정말 많았습니다.~~

2021-06-30 11:44 UTC, merged